### ISSUE TITLE
Add Node.js to environment

### ISSUE THREAD

**Issue by nubs** [facebookarchive/heroku-buildpack-hhvm#11]
One of the most popular heroku buildpacks, [CHH/heroku-buildpack-php](https://github.com/CHH/heroku-buildpack-php) has included node.js support for a while.  Having node.js available for php is becoming increasingly popular due to things like [bower](http://bower.io/), [UglifyJS](http://lisperator.net/uglifyjs/), and other common build tools.

I would like to try out this buildpack, but not having node.js available means I can't do so with many of my current projects, and I doubt I'm the only one.

This definitely would increase the scope of the buildpack but I imagine it would help drive usage as well.

**Comment by henrikbjorn** [comment]
You can make it available with https://github.com/ddollar/heroku-buildpack-multi

**Comment by nubs** [comment]
How did I ever miss that - that looks real useful.  Thanks for pointing that one out.

**Comment by ptarjan** [comment]
Yeah, I don't think we should include `node.js` directly. If you figure out how to do the multi buildpack, please make a wiki page explaining it so someone else doesn't have to re-learn.

**Comment by nubs** [comment]
will do - and I'll link it to this issue.
