### ISSUE TITLE
HHVM version used by HHVM

### ISSUE THREAD

**Issue by henrikbjorn** [facebookarchive/heroku-buildpack-hhvm#5]
It is unclear what version is downloaded from http://dl.hhvm.com

**Comment by ptarjan** [comment]
Good point. That tarball will always be the newest package. Would you rather an option to use an older one?

**Comment by henrikbjorn** [comment]
Rather just have the version name in the tarball name :)

**Comment by riaf** [comment]
@ptarjan I have not seen you updated the package. When are you going to update a package?

**Comment by ptarjan** [comment]
@riaf once i get it to compile on ubuntu 10.04 again. :(
