### ISSUE TITLE
libicudata.so.48: cannot open shared object file

### ISSUE THREAD

**Issue by mbrevda** [facebookarchive/heroku-buildpack-hhvm#9]
When trying to run hhvm from the cli, I get 

```
hhvm: error while loading shared libraries: libicudata.so.48: cannot open shared object file: No such file or directory
```

Here is what I'm running:

``` bash
$ heroku run bash
~ $ vendor/hhvm/hhvm composer.phar selfupdate
vendor/hhvm/hhvm: error while loading shared libraries: libicudata.so.48: cannot open shared object file: No such file or directory
```

**Comment by mbrevda** [comment]
Update: I just realized I need to prefix all command with LD_LIBRARY_PATH=vendor/hhvm/. Is there anyway to have this auto set? Or at least update the docs...

**Comment by ptarjan** [comment]
Yeah, I need to fix this clowny thing.  I'll leave this issue open as a reminder.

**Comment by ClaudiuC** [comment]
Sent a PR at https://github.com/hhvm/heroku-buildpack-hhvm/pull/10
